// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using FlameSensor.RaspberryPi;
using FlameSensor.RaspberryPi.Models;
using Microsoft.Rest;

namespace FlameSensor.RaspberryPi
{
    public static partial class SensorExtensions
    {
        /// <param name='operations'>
        /// Reference to the FlameSensor.RaspberryPi.ISensor.
        /// </param>
        /// <param name='sensorReading'>
        /// Required.
        /// </param>
        public static SensorReading Post(this ISensor operations, SensorReading sensorReading)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ISensor)s).PostAsync(sensorReading);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the FlameSensor.RaspberryPi.ISensor.
        /// </param>
        /// <param name='sensorReading'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<SensorReading> PostAsync(this ISensor operations, SensorReading sensorReading, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<FlameSensor.RaspberryPi.Models.SensorReading> result = await operations.PostWithOperationResponseAsync(sensorReading, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
